# DLLTweaks

[Patches]
AbsorbChance = true           # Spell absorption cap will no longer exceed fPlayerMaxResistance.
PlayerScaleMovement = true    # Player movement speed now does not scale with race height.
